# Generated by Django 3.2.5 on 2021-11-03 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
